# Generated by Django 6.0.5 on 2026-08-08 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_chitfund_chitcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitcontribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
