# Generated by Django 6.0.5 on 2026-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_chitcontribution_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='interest_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Per Month'), ('yearly', 'Per Year')], default='yearly', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest percentage', max_digits=5, null=True),
        ),
    ]
