# Generated by Django 6.0.5 on 2026-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_debt_interest_period_debt_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
