# Generated by Django 6.0.5 on 2026-08-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_debtpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
